[package]
name = "pong"
version = "0.1.0"
authors = ["Kyle Lin <kylejlin.us@gmail.com>"]
edition = "2018"

[dependencies.amethyst]
version = "0.11.0"
features = ["metal"]

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
